# Generated by Django 2.1.5 on 2019-02-02 05:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_name', models.CharField(max_length=50, unique=True)),
                ('contact_no', models.BigIntegerField(max_length=13, unique=True)),
                ('local_address', models.CharField(max_length=200)),
                ('permenent_address', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images')),
                ('ag_email', models.EmailField(max_length=40, unique=True)),
                ('ag_status', models.BooleanField(default=False)),
                ('ad_is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent_allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Master_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp_name', models.CharField(max_length=100)),
                ('msp_address', models.CharField(max_length=150)),
                ('msp_description', models.CharField(max_length=200, null=True)),
                ('msp_status', models.BooleanField(default=False)),
                ('msp_is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Master Properties',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_address', models.CharField(max_length=150)),
                ('pr_rent', models.IntegerField()),
                ('pr_deposite', models.IntegerField()),
                ('pr_is_allocated', models.BooleanField(default=False)),
                ('pr_isactive', models.BooleanField(default=False)),
                ('master_pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Master_Property')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Property_Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_start_date', models.DateField()),
                ('agreement_end_date', models.DateField()),
                ('letter_of_acceptence', models.FileField(upload_to='acceptance_letter')),
                ('tenancy_agreement', models.FileField(upload_to='tenancy_agreement')),
                ('final_rent', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('tenant_intrest_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.BigIntegerField()),
                ('date_of_payment', models.DateField()),
                ('property_allocation1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Property_Allocation')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tn_name', models.CharField(max_length=50)),
                ('tn_contact_no', models.BigIntegerField(max_length=13)),
                ('permenent_address', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images')),
                ('tn_document_type', models.CharField(max_length=30)),
                ('tn_document', models.FileField(upload_to='tenant_docs')),
                ('tn_reference_name', models.CharField(max_length=50)),
                ('tn_reference_address', models.CharField(max_length=200)),
                ('tn_status', models.IntegerField()),
                ('tn_joining_date', models.DateField(auto_now_add=True)),
                ('tn_is_active', models.BooleanField(default=True)),
                ('tn_agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Agent')),
            ],
        ),
        migrations.AddField(
            model_name='property_visit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Tenant'),
        ),
        migrations.AddField(
            model_name='property_visit',
            name='visited_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Property'),
        ),
        migrations.AddField(
            model_name='property_allocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Tenant'),
        ),
        migrations.AddField(
            model_name='agent_allocation',
            name='master_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.Master_Property'),
        ),
    ]
