# Generated by Django 2.1.5 on 2019-02-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property_allocation',
            options={'ordering': ('agreement_start_date',)},
        ),
        migrations.RenameField(
            model_name='rent_collection',
            old_name='property_allocation1',
            new_name='property_allocation',
        ),
        migrations.AlterField(
            model_name='agent',
            name='contact_no',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tn_contact_no',
            field=models.BigIntegerField(),
        ),
    ]
