# Generated by Django 2.1.5 on 2019-02-12 06:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMasterPropertyClone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cln_alias', models.CharField(max_length=30)),
                ('cln_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblMasterProperty')),
            ],
        ),
        migrations.AlterField(
            model_name='tblagent',
            name='ag_contact',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must\n                              be entered in the format: \n                            '+999999999'. 10 digits\n                             allowed.", regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='tblagentallocation',
            name='al_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblMasterPropertyClone'),
        ),
        migrations.AlterField(
            model_name='tblproperty',
            name='pr_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblMasterPropertyClone'),
        ),
        migrations.AlterField(
            model_name='tbltenant',
            name='tn_contact',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must\n                              be entered in the format: \n                            '+999999999'. 10 digits\n                             allowed.", regex='^\\+?1?\\d{10}$')]),
        ),
    ]
