# Generated by Django 2.1.5 on 2019-02-02 07:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TenantManagementApp', '0002_auto_20190202_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_contact', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must\n                              be entered in the format: \n                            '+999999999'. Up to 13 digits\n                             allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('ag_local_address', models.CharField(max_length=255)),
                ('ag_permanent_address', models.CharField(max_length=255)),
                ('ag_profile_image', models.ImageField(blank=True, upload_to='agents/profiles')),
                ('ag_email', models.EmailField(blank=True, max_length=254)),
                ('ag_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agent Details',
            },
        ),
        migrations.CreateModel(
            name='TblAgentAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('al_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblAgent')),
            ],
            options={
                'verbose_name_plural': 'Agent Allocation Details',
            },
        ),
        migrations.CreateModel(
            name='TblMasterProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp_name', models.CharField(default='My Property', max_length=30)),
                ('msp_address', models.CharField(max_length=255)),
                ('msp_description', models.CharField(max_length=255, null=True)),
                ('msp_is_allocated', models.BooleanField(default=False)),
                ('msp_is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Master Properties',
            },
        ),
        migrations.CreateModel(
            name='TblProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_address', models.CharField(max_length=255)),
                ('pr_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_deposite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_is_allocated', models.BooleanField(default=False)),
                ('pr_is_active', models.BooleanField(default=True)),
                ('pr_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblMasterProperty')),
            ],
            options={
                'verbose_name_plural': 'All  Properties',
            },
        ),
        migrations.CreateModel(
            name='TblPropertyAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_agreement_date', models.DateField()),
                ('pa_agreement_and_date', models.DateField()),
                ('pa_acceptance_latter', models.ImageField(upload_to='rent/acceptance_latter')),
                ('pa_tenancy_agreement', models.ImageField(upload_to='rent/tenancy/agreement')),
                ('pa_final_rent', models.FloatField(max_length=10)),
                ('pa_is_allocated', models.BooleanField(default=False)),
                ('pa_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblProperty')),
            ],
            options={
                'verbose_name_plural': 'Property Allocation Details',
            },
        ),
        migrations.CreateModel(
            name='TblRentAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_recipt_no', models.IntegerField()),
                ('rc_month', models.IntegerField(default=1)),
                ('rc_year', models.ImageField(max_length=4, upload_to='')),
                ('rc_pay_off_date', models.DateField()),
                ('rc_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblProperty')),
            ],
            options={
                'verbose_name_plural': 'Rent Collection Details',
            },
        ),
        migrations.CreateModel(
            name='TblTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tn_name', models.CharField(max_length=25)),
                ('tn_contact', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must\n                              be entered in the format: \n                            '+999999999'. Up to 13 digits\n                             allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('tn_permanent_address', models.CharField(max_length=255)),
                ('tn_profile', models.ImageField(upload_to='tenant/profiles')),
                ('tn_document_description', models.CharField(max_length=255, null=True)),
                ('tn_document', models.ImageField(upload_to='tenant/documents')),
                ('tn_reference_name', models.CharField(max_length=25)),
                ('tn_reference_address', models.CharField(max_length=255)),
                ('tn_status', models.IntegerField(default=1)),
                ('tn_joining_date', models.DateField()),
                ('tn_is_active', models.BooleanField(default=True)),
                ('tn_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblAgent')),
            ],
            options={
                'verbose_name_plural': 'Tenant Datails',
            },
        ),
        migrations.CreateModel(
            name='TblVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs_date', models.DateField()),
                ('vs_intrest_status', models.IntegerField(default=1)),
                ('vs_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblProperty')),
                ('vs_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblTenant')),
            ],
            options={
                'verbose_name_plural': 'Visit Details',
            },
        ),
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agent_allocation',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agent_allocation',
            name='master_property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='master_pr_id',
        ),
        migrations.RemoveField(
            model_name='property_allocation',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='property_allocation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='property_visit',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='property_visit',
            name='visited_property',
        ),
        migrations.RemoveField(
            model_name='rent_collection',
            name='property_allocation',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tn_agent_id',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Agent_allocation',
        ),
        migrations.DeleteModel(
            name='Master_Property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Property_Allocation',
        ),
        migrations.DeleteModel(
            name='Property_Visit',
        ),
        migrations.DeleteModel(
            name='Rent_Collection',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AddField(
            model_name='tblpropertyallocation',
            name='pa_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblTenant'),
        ),
        migrations.AddField(
            model_name='tblagentallocation',
            name='al_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenantManagementApp.TblMasterProperty'),
        ),
    ]
