# Generated by Django 2.1.5 on 2019-02-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0002_auto_20190212_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproperty',
            name='pr_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
