# Generated by Django 2.1.5 on 2019-02-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0003_tblproperty_pr_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmasterpropertyclone',
            name='cln_is_master_clone',
            field=models.BooleanField(default=False),
        ),
    ]
