# Generated by Django 2.1.5 on 2019-02-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0005_auto_20190215_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblmasterpropertyclone',
            name='cln_alias',
            field=models.CharField(max_length=100),
        ),
    ]
