# Generated by Django 2.1.5 on 2019-02-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0006_auto_20190215_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_view',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pr_address', models.CharField(max_length=255)),
                ('pr_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_deposite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_is_allocated', models.BooleanField(default=False)),
                ('pr_is_active', models.BooleanField(default=True)),
                ('pr_description', models.CharField(default='', max_length=100)),
                ('cln_alias', models.CharField(max_length=100)),
                ('msp_name', models.CharField(default='My Property', max_length=30)),
                ('msp_address', models.CharField(max_length=255)),
                ('msp_is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'property_view',
                'managed': False,
            },
        ),
    ]
