# Generated by Django 2.1.5 on 2019-02-18 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0007_property_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='allocated_property_view',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pr_address', models.CharField(max_length=255)),
                ('pr_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_deposite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_is_allocated', models.BooleanField(default=False)),
                ('pr_is_active', models.BooleanField(default=True)),
                ('pr_description', models.CharField(default='', max_length=100)),
                ('cln_alias', models.CharField(max_length=100)),
                ('msp_name', models.CharField(default='My Property', max_length=30)),
                ('msp_address', models.CharField(max_length=255)),
                ('msp_is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateField()),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateField()),
                ('ag_contact', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must\n                              be entered in the format: \n                            '+999999999'. 10 digits\n                             allowed.", regex='^\\+?1?\\d{10}$')])),
                ('ag_local_address', models.CharField(max_length=255)),
                ('ag_permanent_address', models.CharField(max_length=255)),
                ('ag_profile_image', models.ImageField(blank=True, upload_to='agents/profiles')),
            ],
            options={
                'db_table': 'agent_allocation_view',
                'managed': False,
            },
        ),
    ]
