# Generated by Django 2.1.5 on 2019-02-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0008_allocated_property_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewMasterProperties',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('msp_name', models.CharField(default='My Property', max_length=30)),
                ('msp_address', models.CharField(max_length=255)),
                ('msp_description', models.CharField(max_length=255)),
                ('msp_is_active', models.BooleanField(default=True)),
                ('no_of_clones', models.BigIntegerField()),
                ('allocated_clones', models.BigIntegerField()),
                ('unallocated_clones', models.BigIntegerField()),
                ('no_of_property', models.BigIntegerField()),
                ('allocated_properties', models.BigIntegerField()),
                ('unallocated_properties', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Master Property ',
                'verbose_name_plural': 'Master Properties',
                'db_table': 'view_master_properties',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='allocated_property_view',
            table='Agent_property_allocation',
        ),
    ]
