# Generated by Django 2.1.5 on 2019-02-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0009_auto_20190226_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpropertyallocation',
            old_name='pa_agreement_and_date',
            new_name='pa_agreement_end_date',
        ),
    ]
