# Generated by Django 2.1.5 on 2019-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0010_auto_20190228_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_is_allocated',
            field=models.BooleanField(default=True),
        ),
    ]
