# Generated by Django 2.1.5 on 2019-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0011_auto_20190228_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_acceptance_latter',
            field=models.ImageField(null=True, upload_to='rent/acceptance_latter'),
        ),
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_agreement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_agreement_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_final_rent',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tblpropertyallocation',
            name='pa_tenancy_agreement',
            field=models.ImageField(null=True, upload_to='rent/tenancy/agreement'),
        ),
    ]
