# Generated by Django 2.1.7 on 2019-03-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0012_auto_20190305_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpropertyallocation',
            name='pa_acceptance_latter',
        ),
        migrations.AddField(
            model_name='tblpropertyallocation',
            name='pa_acceptance_letter',
            field=models.ImageField(null=True, upload_to='rent/acceptance_letter'),
        ),
    ]
