# Generated by Django 2.1.7 on 2019-03-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0015_auto_20190315_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblrentcollection',
            old_name='rc_property',
            new_name='rc_allocation',
        ),
    ]
