# Generated by Django 2.1.7 on 2019-03-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenantManagementApp', '0016_auto_20190315_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrentcollection',
            name='rc_year',
        ),
        migrations.AddField(
            model_name='tblrentcollection',
            name='rc_recipt',
            field=models.ImageField(null=True, upload_to='rent/rent_recipt'),
        ),
        migrations.AlterField(
            model_name='tblrentcollection',
            name='rc_month',
            field=models.DateField(),
        ),
    ]
